module.exports = {
  common: {
    appName: 'Task Mate',
    system: '系统',
    unnamedTraveler: '未命名旅者',
    continue: '继续',
    cancel: '取消',
    confirm: '确认',
    unknown: '未知',
    loadingUnsupported: '当前基础库不支持',
    subscribeTemplateMissing: '未配置订阅模板',
    subscribeUpdated: '订阅已更新',
  },
  icons: {
    arrowUp: '▲',
    arrowDown: '▼',
  },
  tabs: {
    home: '首页',
    mission: '使命',
    collab: '协作',
    archive: '归档',
    achievements: '成长',
    profile: '设置',
  },
  hero: {
    eyebrow: 'Task Mate',
    intro: '在这里查看你的当前状态、快速开始新任务，并掌握今天最值得推进的事项。',
    createTask: '新建任务',
    wisdom: '智慧',
    strength: '体魄',
    agility: '敏捷',
    totalOpen: '活跃任务',
    strengthMini: '💪',
    wisdomMini: '🧠',
    agilityMini: '⚡',
    totalMini: '📜',
  },
  home: {
    todayTitle: '今日焦点',
    todaySubtitle: '优先展示今天需要推进或已经逾期的任务。',
    todayEmpty: '今天没有需要立刻推进的任务。',
    challengeTitle: '每日挑战',
    challengeSubtitle: '系统按日生成挑战任务，不使用 WebSocket，也不做轮询。',
    challengeVirtual: '可接取',
    challengeReward: '奖励',
    challengeAccept: '接取',
    challengeView: '查看',
    challengeEmpty: '今天没有可接取的挑战。',
  },
  mission: {
    title: '使命在身',
    subtitle: '你当前接取并正在推进的任务，包括待确认的重构任务。',
    empty: '当前没有执行中的任务。',
    creatorJoin: ' · ',
  },
  collab: {
    title: '协作与发布',
    subtitle: '你创建的任务，以及需要追踪的历史版本。',
    assigneePrefix: '执行者 ',
    waitingAccept: '等待接取',
    previousVersionShort: '上一版',
    empty: '还没有你发布的任务。',
    historyTitle: '历史版本',
    createdAt: '创建于',
  },
  archive: {
    title: '归档',
    subtitle: '已完成和待检视记录都会进入归档列表。',
    recordedAt: '记录时间',
    progress: '进度',
    empty: '还没有归档任务。',
  },
  achievements: {
    title: '成长面板',
    subtitle: '先保留旧版能力入口，后续再接成就和统计细节。',
    wisdom: '智慧累计',
    strength: '体魄累计',
    agility: '敏捷累计',
    recentArchive: '最近归档',
    currentPointsPrefix: '当前 ',
    currentPointsSuffix: ' 点',
    recordCountSuffix: ' 条记录',
  },
  profile: {
    title: '设置',
    subtitle: '在这里管理你的账号信息、消息提醒和使用指引。',
    userId: '用户 ID',
    nickname: '昵称',
    editNickname: '修改昵称',
    subscribe: '订阅消息',
    onboarding: '新手引导',
    syncTitle: '使用说明',
    sync1: '进入小程序、下拉刷新或完成任务操作后，页面都会更新到最新状态。',
    sync2: '如果任务刚好被别的操作改动，页面会自动刷新，避免看到旧信息。',
    sync3: '建议在开始新任务前先看一眼首页，重要事项和每日挑战都会优先显示在这里。',
    nicknameModalTitle: '修改昵称',
    nicknamePlaceholder: '输入昵称',
    save: '保存',
  },
  onboarding: {
    title: '新手引导',
    subtitle: '第一次进入会自动显示，后面也可以在设置里重新打开。',
    step1Title: '先看首页',
    step1Body: '首页会显示今天需要优先推进的任务和每日挑战，进入小程序时会自动刷新。',
    step2Title: '使命与协作',
    step2Body: '使命是你接取并正在推进的任务，协作是你发布出去并持续跟进状态的任务。',
    step3Title: '任务操作',
    step3Body: '点开任务详情后再操作。进度更新、提交检视、关闭任务这些动作都会写后端再整页刷新。',
    step4Title: '以后怎么找',
    step4Body: '如果后面忘了，可以在设置页重新打开这份引导，不需要重新安装小程序。',
    done: '我知道了',
  },
  detail: {
    dueAt: '截止',
    reward: '奖励',
    creator: '创建者',
    assignee: '执行者',
    completedAt: '完成于',
    closedAt: '关闭于',
    recordedAt: '记录于',
    deleteArchiveTitle: '删除归档',
    deleteArchiveContent: '删除归档后不可恢复，是否继续？',
  },
  actions: {
    shareTask: '分享任务',
    viewPreviousVersion: '查看上一版',
    reworkTask: '重构任务',
    acceptTask: '接取任务',
    acceptRework: '接受重构',
    rejectRework: '拒绝重构',
    cancelRework: '撤销重构',
    updateProgress: '更新进度',
    submitReview: '提交检视',
    continueReview: '退回继续修改',
    completeTask: '完成任务',
    abandonTask: '放弃任务',
    closeTask: '关闭任务',
    restartTask: '重新开启',
    refreshSchedule: '刷新过期时间',
    deleteTask: '删除任务',
    removeStep: '×',
    addStep: '新增步骤',
  },
  create: {
    titleCreate: '创建任务',
    titleRework: '重构任务',
    aiPromptPlaceholder: '一句话描述你想做的任务，交给 AI 帮你起草',
    aiGenerate: '用 AI 生成草案',
    titlePlaceholder: '标题',
    detailPlaceholder: '说明',
    rewardWisdom: '智慧',
    rewardStrength: '体魄',
    rewardAgility: '敏捷',
    selfAssign: '创建后立刻接取',
    subtasksTitle: '任务目标',
    subtaskPlaceholder: '子任务目标',
    submitCreate: '创建任务',
    submitRework: '提交重构',
  },
  status: {
    pending: '待接取',
    in_progress: '进行中',
    review_pending: '待检视',
    pending_confirmation: '待确认',
    completed: '已完成',
    closed: '已关闭',
    refactored: '已重构',
  },
  rewards: {
    wisdom: '智慧',
    strength: '体魄',
    agility: '敏捷',
  },
  errors: {
    loadFailed: '加载失败',
    nicknameRequired: '昵称不能为空',
    updateNicknameFailed: '更新昵称失败',
    aiPromptRequired: '请先输入 AI 提示词',
    aiGenerateFailed: 'AI 生成失败',
    titleRequired: '标题不能为空',
    subtaskRequired: '至少保留一个步骤',
    saveTaskFailed: '保存任务失败',
    previousVersionNotFound: '未找到上一版本任务',
    acceptChallengeFailed: '接取挑战失败',
    taskUpdated: '任务已更新，页面已刷新',
    operationFailed: '操作失败',
    progressUpdateFailed: '更新进度失败',
  },
  dialogs: {
    confirmOperationTitle: '确认操作',
    confirmOperationContent: '是否继续？',
    confirmContinue: '继续',
    confirmCancel: '取消',
    reworkConfirmTitle: '确认重构',
    reworkConfirmContent: '本次重构会删除更早的历史版本，是否继续？',
    closeTaskTitle: '关闭任务',
    closeTaskContent: '关闭后任务将进入可恢复状态，是否继续？',
    deleteTaskTitle: '删除任务',
    deleteTaskContent: '删除后不可恢复，是否继续？',
  },
  share: {
    taskDetailFallback: '任务详情',
  },
  subscribe: {
    guideTitle: '订阅消息',
    guideContent: '如果之前选择了“不再询问”，请在右上角“...” -> 设置 -> 订阅消息 中开启。',
    guideConfirm: '去设置',
    guideAcknowledge: '知道了',
    guideClose: '关闭',
  },
}
