const express = require('express')
const router = express.Router()
const auth = require('../middleware/auth')
const taskController = require('../controllers/taskController')

router.post('/', auth, taskController.createTask)
router.get('/today', auth, taskController.getTodayTasks)
router.get('/challenge', auth, taskController.getChallengeTasks)
router.get('/mission', auth, taskController.getMissionTasks)
router.get('/collab', auth, taskController.getCollabTasks)
router.get('/archive', auth, taskController.getArchivedTasks)
router.get('/', auth, taskController.getAllTasks)
router.get('/:id', auth, taskController.getTask)
router.patch('/:id/progress', auth, taskController.updateProgress)
router.patch('/:id/complete', auth, taskController.completeTask)
router.patch('/:id/abandon', auth, taskController.abandonTask)
router.patch('/:id/close', auth, taskController.closeTask)
router.patch('/:id/restart', auth, taskController.restartTask)
router.post('/:id/rework', auth, taskController.reworkTask)
router.post('/:id/rework/accept', auth, taskController.acceptReworkTask)
router.post('/:id/rework/reject', auth, taskController.rejectReworkTask)

module.exports = router
