module.exports = {
  sensitiveHint: '内容包含敏感词，请调整后再试',
  sensitiveWords: ['赌博', '毒品', '色情', '约炮', '法轮功', '爆炸'],
  defaultDailyTaskPresets: [
    {
      id: 'daily_preset_default',
      title: '完成一组整理练习',
      detail: '这是每天给自己的一项固定推进。',
      dueTime: '23:59',
      rewardType: 'agility',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [{ title: '完成一组整理', total: 1 }],
    },
  ],
  names: {
    system: '星旅系统',
    unnamedTraveler: '未命名旅者',
    traveler: '旅者',
    travelerWithDash: '旅者-',
  },
  sharedTask: {
    title: '分享任务',
    acceptedDetail: '任务已被接取',
  },
  notifications: {
    taskReminder: '任务提醒',
    acceptedStatus: '已接取',
    acceptedTip: '已接取',
    autoAcceptedStatus: '已自动接取',
    autoAcceptedTip: '今日每日任务已按预设自动接取。',
    submitReviewType: '提交检视',
    pendingConfirm: '待确认',
    reviewPendingStatus: '待检视',
    reviewPendingTip: '待检视',
    abandonedStatus: '已放弃',
    abandonedTip: '已放弃',
    closedStatus: '已关闭',
    closedTip: '任务已被关闭',
    reworkPendingDetail: '待确认变更',
    reworkPendingStatus: '待确认变更',
    reworkPendingTip: '任务已重构，请确认变更',
    reworkType: '任务变更',
    rejected: '已拒绝',
    otherRejectedRework: '对方拒绝变更',
    reworkRejectedSuffix: ' · 变更被拒绝',
    reworkCanceledDetail: '变更已撤销',
    reworkCanceledStatus: '变更已撤销',
    reworkCanceledTip: '发布者撤销了重构',
  },
}
