module.exports = {
  sensitiveHint: '内容包含敏感词，请调整后再试',
  sensitiveWords: ['赌博', '毒品', '色情', '约炮', '法轮功', '爆炸'],
  defaultDailyTaskPresets: [
    {
      id: 'daily_default_tidy_desk',
      title: '整理桌面十分钟',
      detail: '把桌面收整干净，给今天的任务腾出一个清爽起点。',
      dueTime: '23:59',
      rewardType: 'agility',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [
        { title: '清走桌面杂物', total: 1 },
        { title: '摆好今天要用的物品', total: 1 },
      ],
    },
    {
      id: 'daily_default_review_plan',
      title: '回看今日重点',
      detail: '花几分钟确认今天最该推进的事情，没有偏离就继续执行。',
      dueTime: '23:59',
      rewardType: 'wisdom',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [
        { title: '写下今天最重要的一件事', total: 1 },
        { title: '删掉一个不重要的分心项', total: 1 },
      ],
    },
    {
      id: 'daily_default_move_body',
      title: '完成一组身体激活',
      detail: '用一组轻量运动把身体带起来，避免一整天都陷在钝感里。',
      dueTime: '23:59',
      rewardType: 'strength',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [
        { title: '完成一组拉伸或热身', total: 1 },
      ],
    },
    {
      id: 'daily_default_quick_clean',
      title: '清理一个小区域',
      detail: '只挑一个小角落推进，不追求彻底，但要求马上可见。',
      dueTime: '23:59',
      rewardType: 'agility',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [
        { title: '选定一个区域', total: 1 },
        { title: '完成清理并恢复整齐', total: 1 },
      ],
    },
    {
      id: 'daily_default_read_notes',
      title: '复盘一页笔记',
      detail: '回看一页旧笔记，把它和今天要做的事重新连起来。',
      dueTime: '23:59',
      rewardType: 'wisdom',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [
        { title: '读完一页旧笔记', total: 1 },
        { title: '补一句今天可执行的提醒', total: 1 },
      ],
    },
    {
      id: 'daily_default_walk',
      title: '出去走一小段',
      detail: '短暂离开当前环境，走一小段路，把注意力重新拉回来。',
      dueTime: '23:59',
      rewardType: 'strength',
      autoAccept: false,
      autoAcceptTime: '06:00',
      subtasks: [
        { title: '完成一段短走动', total: 1 },
      ],
    },
  ],
  names: {
    system: '星旅系统',
    unnamedTraveler: '未命名旅者',
    traveler: '旅者',
    travelerWithDash: '旅者-',
  },
  sharedTask: {
    title: '分享任务',
    acceptedDetail: '任务已被接取',
  },
  notifications: {
    taskReminder: '任务提醒',
    acceptedStatus: '已接取',
    acceptedTip: '已接取',
    autoAcceptedStatus: '已自动接取',
    autoAcceptedTip: '今日每日任务已按预设自动接取。',
    submitReviewType: '提交检视',
    pendingConfirm: '待确认',
    reviewPendingStatus: '待检视',
    reviewPendingTip: '待检视',
    abandonedStatus: '已放弃',
    abandonedTip: '已放弃',
    closedStatus: '已关闭',
    closedTip: '任务已被关闭',
    reworkPendingDetail: '待确认变更',
    reworkPendingStatus: '待确认变更',
    reworkPendingTip: '任务已重构，请确认变更',
    reworkType: '任务变更',
    rejected: '已拒绝',
    otherRejectedRework: '对方拒绝变更',
    reworkRejectedSuffix: ' · 变更被拒绝',
    reworkCanceledDetail: '变更已撤销',
    reworkCanceledStatus: '变更已撤销',
    reworkCanceledTip: '发布者撤销了重构',
  },
}
