export const taskStrings = {
  tabs: {
    mission: { label: '使命在身', hint: '进行中' },
    collab: { label: '奇遇轨迹', hint: '自己发布' },
    archive: { label: '已结星愿', hint: '已完成' },
  },
  status: {
    archived: '已归档',
  },
  icons: {
    status: {
      pending: '⏳',
      in_progress: '🚀',
      review_pending: '📝',
      pending_confirmation: '⏳',
      completed: '✅',
      closed: '📦',
      refactored: '♻️',
      archived: '📂',
    },
    meta: {
      remain: '⏱',
      due: '🗓',
      start: '📅',
      assignee: '🙌',
    },
    toggle: {
      expand: '▶',
      collapse: '✓',
      edit: '🌟',
    },
  },
  metaText: {
    remain: '剩余时间:',
    deleteRemain: '删除倒计时:',
    due: '截止:',
    deleteDue: '删除于:',
    start: '起始:',
    closed: '关闭于:',
    assignee: '执行人:',
    creator: '发起人:',
    unassigned: '未指派',
    closeBlocked: '请执行人放弃任务后再关闭',
    restart: '重启任务',
    close: '关闭任务',
    delete: '删除任务',
    edit: '重构奇遇',
    assign: '指派任务',
    reworkCancel: '撤销修改',
  },
  actions: {
    submitChange: '提交变更',
    submitReview: '提交检视',
    completeTask: '完成任务',
    cancelChange: '取消变更',
    acceptRework: '接受奇遇',
    rejectRework: '拒绝奇遇',
    updateProgress: '更新进度',
    abandonTask: '放弃任务',
    delete: '删除任务',
    restart: '重启任务',
    edit: '重构奇遇',
    assign: '指派任务',
    close: '关闭任务',
    cancelRework: '撤销修改',
  },
  toast: {
    dataRefreshed: '数据已刷新',
    closed: '已关闭',
    closeFail: '关闭失败',
    restarted: '已重启',
    restartFail: '重启失败',
    deleteConfirmTitle: '删除任务',
    deleteConfirmContent: '确认删除该任务吗？',
    deleteConfirmOk: '确认删除',
    cancel: '取消',
    deleted: '已删除',
    abandonTitle: '放弃任务',
    abandonContent: '确认放弃该任务吗？',
    abandonOk: '确认放弃',
    abandoned: '已放弃',
    submitted: '已提交',
    completed: '已完成',
    accepted: '已接受',
    rejected: '已拒绝',
    canceled: '已撤销',
    loadFail: '加载失败',
    noChanges: '未检测到改动，已取消',
    reworked: '奇遇已重构',
    reworkFail: '重构失败',
    missingTitle: '请填写标题',
    missingReward: '请选择属性奖励',
    missingSubtask: '请至少添加一条子任务',
    createAccepted: '任务已接取',
    createOk: '奇遇已发起',
    createFail: '创建失败',
    needOneLine: '请先写一句奇遇描述',
    draftOk: '已生成奇遇草稿',
    draftFail: '生成失败',
    reviewPending: '提交检视待接入',
    assignPending: '指派任务待接入',
    reworkConfirmCancel: '取消',
    reworkConfirmOk: '确认重构',
  },
  modal: {
    titleNew: '发起一场新的奇遇',
    titleRework: '重构奇遇',
    subNew: '写下你想完成的事，其余交给星辰来编织',
    subRework: '奇遇重塑，命途再启',
    oneLineLabel: '一句话奇遇',
    oneLineHint: '先随便描述一下，星旅帮你织成完整奇遇',
    oneLinePlaceholder: '例如：每天睡前冥想 10 分钟，坚持一周',
    aiGenerate: '✨ 由星旅生成',
    closeIcon: '×',
    detailLabel: '详细设定',
    titlePlaceholder: '给这场奇遇起个名字吧',
    detailPlaceholder: '可以写下修行方式、故事背景或注意事项……',
    goalsLabel: '任务目标',
    goalsHint: '列出关键目标即可，不必拆太细',
    addGoal: '+ 添加一步',
    goalPlaceholder: '比如：购买食材 / 完成章节一',
    goalTotalPlaceholder: '目标数',
    removeGoalIcon: '🗑',
    dueLabel: '设定日期与时间',
    dueHintDefault: '默认今天 23:59，可下拉调整',
    dueHintCurrentPrefix: '当前选择：',
    rewardLabel: '星辰奖励',
    rewardHint: '完成后你的角色会增加1点对应属性',
    cancel: '取消',
    submitNew: '发起奇遇',
    submitRework: '发起重构',
    submitSelf: '给自己',
    historyTitle: '上一版奇遇',
    historySub: '仅供查看，不可编辑',
    loading: '加载中...',
    confirmTitle: '确认重构',
    confirmContent: '重构后会删除更早版本。是否继续？',
  },
  subtasks: {
    toggleExpand: '展开任务目标',
    toggleCollapse: '收起任务目标',
    toggleEdit: '编辑任务目标',
  },
  labels: {
    progress: '进度',
    completedAt: '完成于：',
    subtaskFallback: '子任务',
    difficultyMid: '中等',
    difficultyEasy: '简单',
    creatorSystem: '星旅',
  },
  rewards: {
    wisdom: { label: '智慧', icon: '🧠' },
    strength: { label: '力量', icon: '💪' },
    agility: { label: '敏捷', icon: '⚡' },
  },
  time: {
    year: '年',
    month: '月',
    day: '日',
    hour: '时',
    minute: '分',
    justNow: '刚刚',
    minuteAgo: '分钟前',
    hourAgo: '小时前',
    dayAgo: '天前',
    patterns: {
      hour: '(\\d{1,2})\\s*点(半)?',
      breakfast: '早饭|早餐',
      lunch: '午饭|午餐|中饭',
      dinner: '晚饭|晚餐',
      afternoon: '下午|晚上|今晚|夜里',
      noon: '中午',
      morning: '早上|上午|凌晨',
      deadline: '之前|以前|前|截止',
      monthDay: '(\\d{1,2})月(\\d{1,2})日',
      afterTomorrow: '后天',
      tomorrow: '明天',
      today: '今天',
    },
  },
} as const
