const LABELS = {
  cardName: '卡片名称',
  changeDetail: '修改详情',
  changeTime: '修改时间',
  reviewType: '审核类型',
  reviewResult: '审核结果',
  notifyTime: '通知时间',
  rejectReason: '拒绝理由',
  reviewer: '审核人',
  taskName: '任务名称',
  assignee: '执行人',
  startTime: '发布时间',
  dueTime: '截止时间',
  taskStatus: '任务状态',
  itemName: '事项主题',
  remainTime: '剩余时间',
  remindTime: '提醒时间',
  noteMessage: '备注消息',
  status: '状态',
  tip: '温馨提示',
}

const VALUES = {
  taskClosed: '已关闭',
  taskAbandoned: '已放弃',
  taskReworkedPending: '待确认变更',
  reworkAccepted: '已接受',
  reworkRejected: '已拒绝',
  reworkCanceled: '变更已撤销',
  acceptTaskStatus: '已接取',
  reviewTypeTaskChange: '任务变更',
  reviewTypeSubmit: '提交检视',
  reviewResultPending: '待确认',
  rejectReasonAssignee: '对方拒绝变更',
  taskReminder: '任务提醒',
  taskDueSoon: '即将截止',
  taskOverdue: '已过期',
  challengeExpired: '星旅任务已过期并被系统清理',
  expired: '已过期',
  unitDay: '天',
  unitHour: '小时',
  unitMinute: '分钟',
  taskReworkAccepted: '变更已接受',
  taskReworkRejected: '变更已拒绝',
  taskReviewRequired: '待检视',
  taskAssigned: '已接取',
  taskPending: '待接取',
  assigneeTaken: '接取人',
}

module.exports = {
  LABELS,
  VALUES,
}
